#!/bin/bash
# We will use sed to insert the new templates before the closing of the switch/conditional block in PosterCanvas.tsx.

awk '
/\{templateId === '\''landscape-london-11'\'' && \(/ {
    print $0
    flag = 1
    next
}
flag == 1 && /^\s*\}\)$/ {
    # Print the closing of landscape-london-11
    print $0
    
    # Insert new templates
    print "        {templateId === '\''grid-8-center-text'\'' && ("
    print "          <div className=\"w-full h-full flex flex-col\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "            {/* Top Row */}"
    print "            <div className=\"w-full h-[33.33%] min-h-0 flex\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(0, '\''w-full h-full'\'')}</div>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(1, '\''w-full h-full'\'')}</div>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(2, '\''w-full h-full'\'')}</div>"
    print "            </div>"
    print "            {/* Middle Row */}"
    print "            <div className=\"w-full h-[33.34%] min-h-0 flex\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(3, '\''w-full h-full'\'')}</div>"
    print "              {/* Text Block */}"
    print "              <div className=\"w-1/3 h-full flex flex-col items-center justify-center p-2 sm:p-4 text-center\">"
    print "                <div"
    print "                  style={{"
    print "                    fontFamily: textConfig.namesFont,"
    print "                    color: textConfig.namesColor,"
    print "                  }}"
    print "                  className=\"text-lg sm:text-2xl font-light mb-2\""
    print "                >"
    print "                  {textConfig.groomName}<br />&<br />{textConfig.brideName}"
    print "                </div>"
    print "                <div"
    print "                  style={{"
    print "                    fontFamily: textConfig.taglineFont === '\''Montserrat'\'' ? '\''Great Vibes, cursive'\'' : textConfig.taglineFont,"
    print "                    color: textConfig.taglineColor,"
    print "                  }}"
    print "                  className=\"text-xs sm:text-sm italic mb-2 mt-4\""
    print "                >"
    print "                  {textConfig.tagline}"
    print "                </div>"
    print "                <div"
    print "                  style={{"
    print "                    fontFamily: textConfig.dateFont,"
    print "                    color: textConfig.dateColor,"
    print "                  }}"
    print "                  className=\"text-[10px] sm:text-xs font-medium tracking-widest uppercase\""
    print "                >"
    print "                  {textConfig.dateText ? textConfig.dateText.replace(/\\n/g, '\''.'\'') : '\''29.03.2026'\''}"
    print "                </div>"
    print "              </div>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(4, '\''w-full h-full'\'')}</div>"
    print "            </div>"
    print "            {/* Bottom Row */}"
    print "            <div className=\"w-full h-[33.33%] min-h-0 flex\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(5, '\''w-full h-full'\'')}</div>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(6, '\''w-full h-full'\'')}</div>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(7, '\''w-full h-full'\'')}</div>"
    print "            </div>"
    print "          </div>"
    print "        )}"
    print "        {templateId === '\''hero-trio-3'\'' && ("
    print "          <div className=\"w-full h-full flex flex-col\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "            {/* Hero Image */}"
    print "            <div className=\"w-full h-[55%] min-h-0\">"
    print "              {renderSlot(0, '\''w-full h-full'\'')}"
    print "            </div>"
    print "            {/* Text Block */}"
    print "            <div className=\"w-full h-[15%] min-h-0 flex flex-col items-center justify-center p-2 text-center\">"
    print "              <div"
    print "                style={{"
    print "                  fontFamily: textConfig.taglineFont,"
    print "                  color: textConfig.taglineColor,"
    print "                  letterSpacing: '\''3px'\'',"
    print "                }}"
    print "                className=\"text-[10px] sm:text-xs font-bold uppercase mb-2\""
    print "              >"
    print "                {textConfig.tagline}"
    print "              </div>"
    print "              <div"
    print "                style={{"
    print "                  fontFamily: textConfig.namesFont,"
    print "                  color: textConfig.namesColor,"
    print "                }}"
    print "                className=\"text-lg sm:text-2xl font-normal tracking-wide uppercase mb-2\""
    print "              >"
    print "                {textConfig.groomName} {textConfig.connector || '\'&'\''} {textConfig.brideName}"
    print "              </div>"
    print "              <div"
    print "                style={{"
    print "                  fontFamily: textConfig.subtextFont,"
    print "                  color: textConfig.subtextColor,"
    print "                }}"
    print "                className=\"text-[9px] sm:text-[10px] italic max-w-[80%] mx-auto\""
    print "              >"
    print "                {textConfig.subtext}"
    print "              </div>"
    print "            </div>"
    print "            {/* Bottom Photos */}"
    print "            <div className=\"w-full h-[30%] min-h-0 flex\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "              <div className=\"w-1/2 h-full\">{renderSlot(1, '\''w-full h-full'\'')}</div>"
    print "              <div className=\"w-1/2 h-full\">{renderSlot(2, '\''w-full h-full'\'')}</div>"
    print "            </div>"
    print "          </div>"
    print "        )}"
    print "        {templateId === '\''magazine-8'\'' && ("
    print "          <div className=\"w-full h-full flex flex-col\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "            {/* Row 1: Left 1/3, Right 2/3 */}"
    print "            <div className=\"w-full h-[30%] min-h-0 flex\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(0, '\''w-full h-full'\'')}</div>"
    print "              <div className=\"w-2/3 h-full\">{renderSlot(3, '\''w-full h-full'\'')}</div>"
    print "            </div>"
    print "            {/* Row 2: 3 columns */}"
    print "            <div className=\"w-full h-[40%] min-h-0 flex\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(1, '\''w-full h-full'\'')}</div>"
    print "              <div className=\"w-1/3 h-full flex flex-col items-center justify-center p-3 text-center bg-[#8b988f] text-white\">"
    print "                <div"
    print "                  style={{"
    print "                    fontFamily: textConfig.subtextFont,"
    print "                  }}"
    print "                  className=\"text-[8px] sm:text-[9px] uppercase tracking-widest mb-4 opacity-80\""
    print "                >"
    print "                  FROM TODAY WE WILL GROW OLD TOGETHER"
    print "                </div>"
    print "                <div"
    print "                  style={{"
    print "                    fontFamily: textConfig.dateFont,"
    print "                    lineHeight: 1.1,"
    print "                  }}"
    print "                  className=\"text-3xl sm:text-4xl font-normal mb-4\""
    print "                >"
    print "                  {textConfig.dateText ? textConfig.dateText.replace(/\\./g, '\''\\n'\'') : '\''29\\n03\\n26'\''}"
    print "                </div>"
    print "                <div"
    print "                  style={{"
    print "                    fontFamily: textConfig.namesFont,"
    print "                  }}"
    print "                  className=\"text-[10px] sm:text-xs font-medium tracking-wide uppercase flex flex-col items-center\""
    print "                >"
    print "                  <span>{textConfig.groomName}</span>"
    print "                  <span className=\"text-xl my-1\" style={{ fontFamily: '\''Great Vibes, cursive'\'' }}>&</span>"
    print "                  <span>{textConfig.brideName}</span>"
    print "                </div>"
    print "              </div>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(4, '\''w-full h-full'\'')}</div>"
    print "            </div>"
    print "            {/* Row 3: 3 columns, last col is 2 stacked */}"
    print "            <div className=\"w-full h-[30%] min-h-0 flex\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(2, '\''w-full h-full'\'')}</div>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(5, '\''w-full h-full'\'')}</div>"
    print "              <div className=\"w-1/3 h-full flex flex-col\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "                <div className=\"w-full h-[50%] min-h-0\">{renderSlot(6, '\''w-full h-full'\'')}</div>"
    print "                <div className=\"w-full h-[50%] min-h-0\">{renderSlot(7, '\''w-full h-full'\'')}</div>"
    print "              </div>"
    print "            </div>"
    print "          </div>"
    print "        )}"
    print "        {templateId === '\''asymmetric-7'\'' && ("
    print "          <div className=\"w-full h-full flex flex-col\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "            {/* Row 1 */}"
    print "            <div className=\"w-full h-[33.33%] min-h-0 flex\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(0, '\''w-full h-full'\'')}</div>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(1, '\''w-full h-full'\'')}</div>"
    print "              <div className=\"w-1/3 h-full flex flex-col items-start justify-center p-4\">"
    print "                <div"
    print "                  style={{"
    print "                    fontFamily: textConfig.taglineFont,"
    print "                    color: textConfig.taglineColor,"
    print "                  }}"
    print "                  className=\"text-xl sm:text-2xl uppercase tracking-widest leading-snug font-medium\""
    print "                >"
    print "                  ETERNAL<br/>PROMISE"
    print "                </div>"
    print "              </div>"
    print "            </div>"
    print "            {/* Row 2 */}"
    print "            <div className=\"w-full h-[33.34%] min-h-0 flex\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(2, '\''w-full h-full'\'')}</div>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(3, '\''w-full h-full'\'')}</div>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(4, '\''w-full h-full'\'')}</div>"
    print "            </div>"
    print "            {/* Row 3 */}"
    print "            <div className=\"w-full h-[33.33%] min-h-0 flex\" style={{ gap: `${posterSettings.gap}px` }}>"
    print "              <div className=\"w-1/3 h-full flex flex-col items-center justify-end p-4 text-center\">"
    print "                <div"
    print "                  style={{"
    print "                    fontFamily: textConfig.subtextFont,"
    print "                    color: textConfig.subtextColor,"
    print "                  }}"
    print "                  className=\"text-[8px] sm:text-[9px] font-bold uppercase tracking-widest leading-relaxed mb-4\""
    print "                >"
    print "                  LET ETERNAL MOMENT<br/>BECOME YOUR LOVE STORY"
    print "                </div>"
    print "              </div>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(5, '\''w-full h-full'\'')}</div>"
    print "              <div className=\"w-1/3 h-full\">{renderSlot(6, '\''w-full h-full'\'')}</div>"
    print "            </div>"
    print "          </div>"
    print "        )}"
    
    flag = 0
    next
}
{ print $0 }
' src/components/PosterCanvas.tsx > temp.tsx && mv temp.tsx src/components/PosterCanvas.tsx
